/*
 * commit.h
 *
 *  Created on: Apr 25, 2021
 *      Author: jwilson
 */

#ifndef INC_COMMIT_H_
#define INC_COMMIT_H_

typedef enum uint8_t {
	COMMIT_LED_ROTPIC = 0,

	COMMIT_LED_ADSR_OSC_FILT_A,
	COMMIT_LED_ADSR_OSC_FILT_D,
	COMMIT_LED_ADSR_OSC_FILT_S,
	COMMIT_LED_ADSR_OSC_FILT_R,
	COMMIT_LED_ADSR_SUB_FILT_A,
	COMMIT_LED_ADSR_SUB_FILT_D,
	COMMIT_LED_ADSR_SUB_FILT_S,
	COMMIT_LED_ADSR_SUB_FILT_R,
	COMMIT_LED_ADSR_OSC_AMP_A,
	COMMIT_LED_ADSR_OSC_AMP_D,
	COMMIT_LED_ADSR_OSC_AMP_S,
	COMMIT_LED_ADSR_OSC_AMP_R,
	COMMIT_LED_ADSR_SUB_AMP_A,
	COMMIT_LED_ADSR_SUB_AMP_D,
	COMMIT_LED_ADSR_SUB_AMP_S,
	COMMIT_LED_ADSR_SUB_AMP_R,

	COMMIT_LED_OSC1_SAW,
	COMMIT_LED_OSC1_SQU,
	COMMIT_LED_OSC1_MIX,
	COMMIT_LED_OSC1_FILT,
	COMMIT_LED_OSC1_DRIVE,
	COMMIT_LED_OSC1_TO_OSC2,
	COMMIT_LED_OSC2_SAW,
	COMMIT_LED_OSC2_SQU,
	COMMIT_LED_OSC2_NOISE,
	COMMIT_LED_OSC2_ONLY,
	COMMIT_LED_OSC2_PREFILT,
	COMMIT_LED_OSC2_FILT,
	COMMIT_LED_OSC2_DRIVE,
	COMMIT_LED_OSC_AMP_OUT,
	COMMIT_LED_SUB_AMP_OUT,
	COMMIT_LED_SUB_SQU,
	COMMIT_LED_SUB_NOISE,
	COMMIT_LED_SUB_MIX,
	COMMIT_LED_SUB_TO_OSC2,
	COMMIT_LED_SUB_FILT_OUT,
	COMMIT_LED_FX_DRY,
	COMMIT_LED_FX_WET,
	COMMIT_LED_FX_FEEDBACK,

} commit_cycle_t;

void commit_30hz_timer(void);

#endif /* INC_COMMIT_H_ */
